spring.application.name=app
api.weather.root.url=https://prevision-meteo.ch/services/json
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=weather
spring.jpa.hibernate.ddl-auto=validate